server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://api:8081/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 180s;
    }

    location = /metrics.json {
        add_header Cache-Control "no-store";
        try_files $uri =404;
    }

    location = /app.js {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }

    location = /style.css {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
